### ISSUE TITLE
"client" permission required

### ISSUE THREAD

**Issue by CBenni** [outsideris/slack-invite-automation#83]
So I tried to set this up, but when attempting the curl request, I got the following response:

`{
    "ok": false,
    "error": "missing_scope",
    "needed": "client",
    "provided": "admin,identify,users.profile:write"
}`

Apparently slack now requires client permissions? I replaced the token with the token I grabbed by opening the slack app devtools, and it worked fine.

Probably not much you can do about this, but I wanted to give a heads up and ask if maybe you know a nicer way to handle this.

**Comment by arahansa** [comment]
Hi I think.. When you install Slack app.. You need add client permission manually..

for example.. in your slack app page, `Settings - Install app` menu..  
you can see this `Install App` button.. copy the link of that button and
![2017-03-08 11 32 52](https://cloud.githubusercontent.com/assets/6437210/23687677/06eaf750-03f3-11e7-9161-3a1d8c680ee1.png)

 you can see that link like this.. 
```
https://slack.com/oauth/authorize?&client_id=(your client id)&team=(teamId)&install_redirect=install-on-team&scope=admin
```

you need to make that scope like this
```
 &scope=admin+client 
```
and type in your browser to move that link.. 
for me, it works

**Comment by CBenni** [comment]
Ah, interesting, ill try that out; Didnt really expect that to work. Thanks!

**Comment by ghost** [comment]
Thank you! Plus one for the solution.

**Comment by dankeller** [comment]
Worked! May need to update the readme.

**Comment by outsideris** [comment]
I updated README. Please check https://github.com/outsideris/slack-invite-automation#issue-token .

**Comment by bipin-rudder** [comment]
The issue seems to be still present. Above approaches are failing to work : https://github.com/outsideris/slack-invite-automation/issues/146#issuecomment-775217681.
Any one able to get past through this?
